name: "Update Updates Release Channel Expo.plist"
description: "Update the Expo.plist file"
author: "Brune04"
inputs:
    expo-plist-path:
        description: "Relative path for the Expo.plist file."
        required: true
    updates-release-channel:
        description: "The Expo Updates Release Channel."
        required: true
    print-file:
        description: "Output the Expo.plist file in console"
        required: false
runs:
    using: "node12"
    main: "dist/index.js"
branding:
    icon: "file"
    color: "blue"
