name: sample

on:
    pull_request:
        paths-ignore:
            - "**.md"
    push:
        branches:
            - main
            - releases/*
        paths-ignore:
            - "**.md"

jobs:
    local-version:
        runs-on: macos-latest
        name: Run local action version
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Update Expo.plist
              uses: ./
              with:
                  expo-plist-path: "./samples/Expo.plist"
                  updates-release-channel: "dev-2.0"
                  print-file: true

            - name: Update Expo-1.plist
              uses: ./
              with:
                  expo-plist-path: "./samples/Expo.plist"
                  updates-release-channel: "dev-1.0"
                  print-file: true
